# ============================
# ms-search Configuration
# Managed by Config Server
# ============================

# Random port (assigned by OS)
server.port=0

# No database needed - this ms only calls ms-bundle via HTTP

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
