# ==============================================================================
# 00 - Namespace y Secrets
# ==============================================================================
# Namespace: Aísla todos los recursos del proyecto en un espacio lógico separado
# dentro de Kubernetes. Esto evita conflictos con otros proyectos en el cluster.
#
# Secret: Almacena datos sensibles (contraseñas) codificados en base64.
# Kubernetes los monta como variables de entorno en los pods que los necesiten.
# ==============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: travel-agency

---

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: travel-agency
type: Opaque
data:
  # "root" en base64
  MYSQL_USER: cm9vdA==
  # "clave1234" en base64
  MYSQL_ROOT_PASSWORD: Y2xhdmUxMjM0
