# ============================
# ms-reservation - Local Properties
# ============================
spring.application.name=ms-reservation

# Import configuration from Config Server
spring.config.import=configserver:http://localhost:8888
