# ============================
# ms-bundle - Local Properties
# ============================
# The application name MUST match the config file name in Config Server
spring.application.name=ms-bundle

# Import configuration from Config Server
# On startup, this ms asks Config Server (port 8888) for its config
spring.config.import=configserver:http://localhost:8888