# Fixed Port for Config Server
server.port=8888

spring.application.name=config-server

# Local file search
spring.profiles.active=native

# Path to save files
spring.cloud.config.server.native.search-locations=classpath:/configuraciones/

# Eureka Client - register so ms can find config-server by name
eureka.client.service-url.defaultZone=http://localhost:8761/eureka