# ============================
# ms-tracking - Local Properties
# ============================
spring.application.name=ms-tracking

# Import configuration from Config Server
spring.config.import=configserver:http://localhost:8888
