# ============================
# ms-reports - Local Properties
# ============================
spring.application.name=ms-reports

# Import configuration from Config Server
spring.config.import=configserver:http://localhost:8888
